
@rootUrl = http://localhost:8000
#API list


### Check the server status
GET {{rootUrl}}

### Auth API

### Post new user
POST {{rootUrl}}/api/v1/auth/register
Content-Type: application/json

{
  "fName": "John3",
  "lName": "Doe33",
  "email": "john8@doe.com",
  "phone": "0455667788",
  "password": "Password@123"
}

### Post to activate user
POST {{rootUrl}}/api/v1/auth/activate-user
Content-Type: application/json

{
  "sessionId": "687ccf4d214567f16d60dfcd",
  "t": "b807d164-7fcc-4b0a-92bd-f600991ad41b"
}

### Login user
POST {{rootUrl}}/api/v1/auth/login
Content-Type: application/json

{
  "email": "john@doe.com",
  "password": "Password@1234"
}

### Get user profile
GET {{rootUrl}}/api/v1/users/profile
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZG9lLmNvbSIsImlhdCI6MTc1MzE1MDMzNiwiZXhwIjoxNzUzMTUxMjM2fQ.J7-JPfdrSTvPJyqJjq6qPkWOZ1i3lOdyElSW1boZhE0


### Renew accessJWT
GET {{rootUrl}}/api/v1/auth/renew-jwt
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZG9lLmNvbSIsImlhdCI6MTc1MzE1NjA2OCwiZXhwIjoxNzU1NzQ4MDY4fQ.usuUmQy_5tUGlZL69ZLsNkDifad32dW1arXTbe0Mivg


### request OTP
POST {{rootUrl}}/api/v1/auth/otp 
Content-Type: application/json

{
  "email": "john@doe.com"
}


### Reset password
POST {{rootUrl}}/api/v1/auth/reset-password 
Content-Type: application/json

{
  "email": "john@doe.com",
  "password": "Password@1234",
  "otp": 7120
}
