
@rootUrl = http://localhost:8000
#API list


### Check the server status
GET {{rootUrl}}

### Auth API

### Post new user
POST {{rootUrl}}/api/v1/auth/register
Content-Type: application/json

{
  "fName": "John3",
  "lName": "Doe33",
  "email": "john8@doe.com",
  "phone": "0455667788",
  "password": "Password@123"
}

### Post to activate user
POST {{rootUrl}}/api/v1/auth/activate-user
Content-Type: application/json

{
  "sessionId": "687ccf4d214567f16d60dfcd",
  "t": "b807d164-7fcc-4b0a-92bd-f600991ad41b"
}

### Login user
POST {{rootUrl}}/api/v1/auth/login
Content-Type: application/json

{
  "email": "john@doe.com",
  "password": "Password@123"
}

### Get user profile
GET {{rootUrl}}/api/v1/users/profile
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZG9lLmNvbSIsImlhdCI6MTc1MzE1MDMzNiwiZXhwIjoxNzUzMTUxMjM2fQ.J7-JPfdrSTvPJyqJjq6qPkWOZ1i3lOdyElSW1boZhE0


### Renew accessJWT
GET {{rootUrl}}/api/v1/auth/renew-jwt
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZG9lLmNvbSIsImlhdCI6MTc1MzI3MzAwNCwiZXhwIjoxNzU1ODY1MDA0fQ.bewGqfDhYomXOHkFb16mAVCYshLogsr6nxOSzctPJug


### request OTP
POST {{rootUrl}}/api/v1/auth/otp 
Content-Type: application/json

{
  "email": "john@doe.com"
}


### Reset password
POST {{rootUrl}}/api/v1/auth/reset-password 
Content-Type: application/json

{
  "email": "john@doe.com",
  "password": "Password@1234",
  "otp": 7120
}


### Book API

### Post new book
POST {{rootUrl}}/api/v1/books
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZG9lLmNvbSIsImlhdCI6MTc1MzI2NTUyOSwiZXhwIjoxNzUzMjY2NDI5fQ.HU8i_4pD9sYSDhbrBLJ9ahURullwoRX1Tr9WMgmvFfE

{
  "title": "Sapiens",
  "year": 2005,
  "author": "Yuval Noah Harari",
  "imgUrl": "https://m.media-amazon.com/images/I/713jIoMO3UL._SY522_.jpg",
  "isbn": "978006231609733",
  "genre": "Anthropology",
  "description": "This is a description"
}


### Get book(s)
GET {{rootUrl}}/api/v1/books


### Get book(s) for admin
GET {{rootUrl}}/api/v1/books/admin
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZG9lLmNvbSIsImlhdCI6MTc1MzI3MjM5MywiZXhwIjoxNzUzMjczMjkzfQ.rtGfvkvpb-kBs9Hz6ZN_DeBmHqRH4_ie0ONhcEna9fE
