const books = [
  {
    status: "active",
    slug: "clean-code",
    title: "Clean Code: A Handbook of Agile Software Craftsmanship",
    year: 2008,
    author: "Robert C. Martin",
    imgUrl: "https://m.media-amazon.com/images/I/41SH-SvWPxL.jpg",
    imageList: ["https://m.media-amazon.com/images/I/41SH-SvWPxL.jpg"],
    isbn: 9780132350884,
    genre: "Software Development",
    available: true,
    averageRating: 4.7,
    description:
      "A book about writing clean and maintainable code, with principles and best practices for software developers.",
    expectedAvailable: null,
    addedBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
    lastUpdateBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
  },
  {
    status: "active",
    slug: "the-pragmatic-programmer",
    title: "The Pragmatic Programmer: Your Journey To Mastery",
    year: 1999,
    author: "Andrew Hunt and David Thomas",
    imgUrl: "https://m.media-amazon.com/images/I/41as+WafrFL.jpg",
    imageList: ["https://m.media-amazon.com/images/I/41as+WafrFL.jpg"],
    isbn: 9780135957059,
    genre: "Software Development",
    available: true,
    averageRating: 4.8,
    description:
      "A classic book covering pragmatic thinking, career development, and software craftsmanship.",
    expectedAvailable: null,
    addedBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
    lastUpdateBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
  },
  {
    status: "active",
    slug: "design-patterns",
    title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    year: 1994,
    author: "Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides",
    imgUrl: "https://m.media-amazon.com/images/I/41T0lDqaI+L.jpg",
    imageList: ["https://m.media-amazon.com/images/I/41T0lDqaI+L.jpg"],
    isbn: 9780201633610,
    genre: "Software Engineering",
    available: true,
    averageRating: 4.6,
    description: "The classic book on design patterns in software engineering.",
    expectedAvailable: null,
    addedBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
    lastUpdateBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
  },
  {
    status: "active",
    slug: "code-complete",
    title: "Code Complete: A Practical Handbook of Software Construction",
    year: 2004,
    author: "Steve McConnell",
    imgUrl: "https://m.media-amazon.com/images/I/41F4MHFxuwL.jpg",
    imageList: ["https://m.media-amazon.com/images/I/41F4MHFxuwL.jpg"],
    isbn: 9780735619678,
    genre: "Software Development",
    available: true,
    averageRating: 4.7,
    description:
      "One of the most comprehensive books on the construction and quality of software.",
    expectedAvailable: null,
    addedBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
    lastUpdateBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
  },
  {
    status: "active",
    slug: "refactoring",
    title: "Refactoring: Improving the Design of Existing Code",
    year: 1999,
    author: "Martin Fowler",
    imgUrl: "https://m.media-amazon.com/images/I/41W3-MQfdKL.jpg",
    imageList: ["https://m.media-amazon.com/images/I/41W3-MQfdKL.jpg"],
    isbn: 9780201485677,
    genre: "Software Development",
    available: true,
    averageRating: 4.6,
    description:
      "The book introduces a practical methodology to improve the design of existing code.",
    expectedAvailable: null,
    addedBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
    lastUpdateBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
  },
  {
    status: "active",
    slug: "the-mythical-man-month",
    title: "The Mythical Man-Month: Essays on Software Engineering",
    year: 1975,
    author: "Frederick P. Brooks Jr.",
    imgUrl: "https://m.media-amazon.com/images/I/41kNKid-VTL.jpg",
    imageList: ["https://m.media-amazon.com/images/I/41kNKid-VTL.jpg"],
    isbn: 9780201835953,
    genre: "Software Engineering",
    available: true,
    averageRating: 4.5,
    description:
      "Brooks' classic on the challenges of software project management.",
    expectedAvailable: null,
    addedBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
    lastUpdateBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
  },
  {
    status: "active",
    slug: "effective-java",
    title: "Effective Java",
    year: 2008,
    author: "Joshua Bloch",
    imgUrl: "https://m.media-amazon.com/images/I/418y7vZTuoL.jpg",
    imageList: ["https://m.media-amazon.com/images/I/418y7vZTuoL.jpg"],
    isbn: 9780321356680,
    genre: "Java",
    available: true,
    averageRating: 4.7,
    description:
      "Best practices and techniques for writing efficient and maintainable Java code.",
    expectedAvailable: null,
    addedBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
    lastUpdateBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
  },
  {
    status: "active",
    slug: "nodejs-design-patterns",
    title: "Node.js Design Patterns",
    year: 2014,
    author: "Mario Casciaro",
    imgUrl: "https://m.media-amazon.com/images/I/41DqpydbfxL.jpg",
    imageList: ["https://m.media-amazon.com/images/I/41DqpydbfxL.jpg"],
    isbn: 9781783287311,
    genre: "Node.js",
    available: true,
    averageRating: 4.6,
    description:
      "Learn how to design scalable and maintainable Node.js applications using various patterns.",
    expectedAvailable: null,
    addedBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
    lastUpdateBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
  },
  {
    status: "active",
    slug: "javascript-the-good-parts",
    title: "JavaScript: The Good Parts",
    year: 2008,
    author: "Douglas Crockford",
    imgUrl: "https://m.media-amazon.com/images/I/51M7NSR2q7L.jpg",
    imageList: ["https://m.media-amazon.com/images/I/51M7NSR2q7L.jpg"],
    isbn: 9780596517748,
    genre: "JavaScript",
    available: true,
    averageRating: 4.6,
    description:
      "An essential guide to the best parts of JavaScript and how to write elegant, efficient code.",
    expectedAvailable: null,
    addedBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
    lastUpdateBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
  },
  {
    status: "active",
    slug: "learning-python",
    title: "Learning Python",
    year: 2013,
    author: "Mark Lutz",
    imgUrl: "https://m.media-amazon.com/images/I/41BvPSqZlOL.jpg",
    imageList: ["https://m.media-amazon.com/images/I/41BvPSqZlOL.jpg"],
    isbn: 9781449355739,
    genre: "Python",
    available: true,
    averageRating: 4.7,
    description:
      "A comprehensive guide to Python programming, ideal for beginners and experienced developers alike.",
    expectedAvailable: null,
    addedBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
    lastUpdateBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
  },
  {
    status: "active",
    slug: "the-clean-coder",
    title: "The Clean Coder: A Code of Conduct for Professional Programmers",
    year: 2011,
    author: "Robert C. Martin",
    imgUrl: "https://m.media-amazon.com/images/I/41By+4ddVgL.jpg",
    imageList: ["https://m.media-amazon.com/images/I/41By+4ddVgL.jpg"],
    isbn: 9780137081074,
    genre: "Software Development",
    available: true,
    averageRating: 4.5,
    description:
      "A guide for software developers to improve professionalism and effectiveness.",
    expectedAvailable: null,
    addedBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
    lastUpdateBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
  },
  {
    status: "active",
    slug: "soft-skills",
    title: "Soft Skills: The Software Developer's Life Manual",
    year: 2014,
    author: "John Sonmez",
    imgUrl: "https://m.media-amazon.com/images/I/51BpbmpHfhL.jpg",
    imageList: ["https://m.media-amazon.com/images/I/51BpbmpHfhL.jpg"],
    isbn: 9781617292231,
    genre: "Career Development",
    available: true,
    averageRating: 4.6,
    description:
      "A guide for software developers to enhance their career by focusing on skills outside of coding.",
    expectedAvailable: null,
    addedBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
    lastUpdateBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
  },
  {
    status: "active",
    slug: "you-dont-know-js-1",
    title: "You Don't Know JS: Scope & Closures",
    year: 2014,
    author: "Kyle Simpson",
    imgUrl: "https://m.media-amazon.com/images/I/41hoQeg+7QL.jpg",
    imageList: ["https://m.media-amazon.com/images/I/41hoQeg+7QL.jpg"],
    isbn: 9781449335588,
    genre: "JavaScript",
    available: true,
    averageRating: 4.8,
    description:
      "Deep dive into JavaScript's scope and closures to help developers understand complex JS concepts.",
    expectedAvailable: null,
    addedBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
    lastUpdateBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
  },
  {
    status: "active",
    slug: "javascript-the-good-parts2",
    title: "JavaScript: The Good Parts",
    year: 2008,
    author: "Douglas Crockford",
    imgUrl: "https://m.media-amazon.com/images/I/51J1nSgl-Ql.jpg",
    imageList: ["https://m.media-amazon.com/images/I/51J1nSgl-Ql.jpg"],
    isbn: 9780596517749,
    genre: "JavaScript",
    available: true,
    averageRating: 4.6,
    description:
      "Focuses on the best features of JavaScript, helping developers avoid pitfalls.",
    expectedAvailable: null,
    addedBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
    lastUpdateBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
  },
  {
    status: "active",
    slug: "elegant-objects",
    title: "Elegant Objects: The Good Parts of Object-Oriented Programming",
    year: 2017,
    author: "Yegor Bugayenko",
    imgUrl: "https://m.media-amazon.com/images/I/51g5Pa+F-TL.jpg",
    imageList: ["https://m.media-amazon.com/images/I/51g5Pa+F-TL.jpg"],
    isbn: 9781537024901,
    genre: "Software Development",
    available: true,
    averageRating: 4.4,
    description:
      "A deep dive into object-oriented programming and design with best practices.",
    expectedAvailable: null,
    addedBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
    lastUpdateBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
  },
  {
    status: "active",
    slug: "the-art-of-programming",
    title: "The Art of Computer Programming",
    year: 1968,
    author: "Donald E. Knuth",
    imgUrl: "https://m.media-amazon.com/images/I/51h+lxh8q2L.jpg",
    imageList: ["https://m.media-amazon.com/images/I/51h+lxh8q2L.jpg"],
    isbn: 9780321751041,
    genre: "Algorithms",
    available: true,
    averageRating: 4.7,
    description:
      "A series of books that explore algorithms and data structures in-depth.",
    expectedAvailable: null,
    addedBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
    lastUpdateBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
  },
  {
    status: "active",
    slug: "clean-architecture",
    title:
      "Clean Architecture: A Craftsman's Guide to Software Structure and Design",
    year: 2017,
    author: "Robert C. Martin",
    imgUrl: "https://m.media-amazon.com/images/I/41W6l8SY2vL.jpg",
    imageList: ["https://m.media-amazon.com/images/I/41W6l8SY2vL.jpg"],
    isbn: 9780134494166,
    genre: "Software Architecture",
    available: true,
    averageRating: 4.6,
    description:
      "A guide to creating clean and maintainable software architecture.",
    expectedAvailable: null,
    addedBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
    lastUpdateBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
  },
  {
    status: "active",
    slug: "the-challenge-of-programming",
    title: "The Challenge of Programming: Algorithmic Problem Solving",
    year: 2019,
    author: "John Carter",
    imgUrl: "https://m.media-amazon.com/images/I/51d2dmt1QlL.jpg",
    imageList: ["https://m.media-amazon.com/images/I/51d2dmt1QlL.jpg"],
    isbn: 9780429023167,
    genre: "Algorithms",
    available: true,
    averageRating: 4.4,
    description:
      "A collection of algorithmic challenges to improve your programming skills.",
    expectedAvailable: null,
    addedBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
    lastUpdateBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
  },
  {
    status: "active",
    slug: "structure-and-interpretation",
    title: "Structure and Interpretation of Computer Programs",
    year: 1995,
    author: "Harold Abelson and Gerald Jay Sussman",
    imgUrl: "https://m.media-amazon.com/images/I/51g+Q1u6rKL.jpg",
    imageList: ["https://m.media-amazon.com/images/I/51g+Q1u6rKL.jpg"],
    isbn: 9780262510875,
    genre: "Computer Science",
    available: true,
    averageRating: 4.7,
    description:
      "A fundamental computer science book exploring the principles of programming languages.",
    expectedAvailable: null,
    addedBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
    lastUpdateBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
  },
  {
    status: "active",
    slug: "patterns-of-enterprise-application-architecture",
    title: "Patterns of Enterprise Application Architecture",
    year: 2002,
    author: "Martin Fowler",
    imgUrl: "https://m.media-amazon.com/images/I/51JrX6bR8qL.jpg",
    imageList: ["https://m.media-amazon.com/images/I/51JrX6bR8qL.jpg"],
    isbn: 9780321127426,
    genre: "Software Architecture",
    available: true,
    averageRating: 4.4,
    description:
      "A book that provides common patterns and solutions for enterprise application design.",
    expectedAvailable: null,
    addedBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
    lastUpdateBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
  },
  {
    status: "active",
    slug: "introduction-to-algorithms",
    title: "Introduction to Algorithms",
    year: 2009,
    author:
      "Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, Clifford Stein",
    imgUrl: "https://m.media-amazon.com/images/I/51yIEqkj8kL.jpg",
    imageList: ["https://m.media-amazon.com/images/I/51yIEqkj8kL.jpg"],
    isbn: 9780262033848,
    genre: "Algorithms",
    available: true,
    averageRating: 4.7,
    description:
      "An in-depth introduction to algorithms, providing comprehensive coverage of algorithmic principles.",
    expectedAvailable: null,
    addedBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
    lastUpdateBy: { name: "Admin User", adminId: "60c72b2f9b1d4c3a5e8f1f1a" },
  },
];

export default books;
